<template>
  <main>
    <section>
      <book-Comp></book-Comp>
      <book-Comp></book-Comp>
      <book-Comp></book-Comp>
      <book-Comp></book-Comp>
      <book-Comp></book-Comp>
      <book-Comp></book-Comp>
      <book-Comp></book-Comp>
      <book-Comp></book-Comp>
      <book-Comp></book-Comp>
      <book-Comp></book-Comp>
    </section>
  </main>
</template>